### ISSUE TITLE
invalid type provided: \"object\"

### ISSUE THREAD

**Issue by samuelyeats** [contentful-labs/travis-notify-geckoboard#3]
Getting this error, any ideas?

Unhandled rejection OperationalError: {"message":"invalid type provided: \"object\""}

**Comment by darryla** [comment]
@sdepold Same problem here.

**Comment by jadatkins** [comment]
That's what I've got, both on Travis and when I tried locally. Here's my shell log:

```
$ export GECKOBOARD_API_KEY='xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
$ export GECKOBOARD_WIDGET_KEY='xxxxxx-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
$ export TRAVIS_BRANCH=master
$ export TRAVIS_BUILD_NUMBER=1234
$ export TRAVIS_REPO_SLUG='jadatkins/TutorfairWebsite'
$ export TRAVIS_TEST_RESULT=0
$ travis-notify-geckoboard -a $GECKOBOARD_API_KEY -w $GECKOBOARD_WIDGET_KEY
Unhandled rejection OperationalError: {"message":"invalid type provided: \"object\""}

    at BufferList.<anonymous> (/usr/local/lib/node_modules/travis-notify-geckoboard/node_modules/questor/index.js:40:25)
    at BufferList.end (/usr/local/lib/node_modules/travis-notify-geckoboard/node_modules/questor/node_modules/bl/bl.js:75:10)
    at IncomingMessage.onend (_stream_readable.js:485:10)
    at IncomingMessage.g (events.js:180:16)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:929:16
    at process._tickCallback (node.js:419:13)
```

@ehd Do you know what we should do?

**Comment by jadatkins** [comment]
The error is [on this line in this file](https://gist.github.com/jadatkins/9b331adef7d862953c77#file-index-js-L40).

**Comment by jadatkins** [comment]
Oh, I see. This is a JSON object actually being returned by Travis, with an HTTP 400: `{"message":"invalid type provided: \"object\""}`

**Comment by jadatkins** [comment]
I've [fixed it](https://github.com/contentful-labs/travis-notify-geckoboard/pull/4). Now it's just a matter of getting that accepted into the version installed by `npm`.

**Comment by jadatkins** [comment]
Turns out there's already a pull request #1 that fixes this.
